// // This file is automatically generated. Do not edit it directly.
// import { createClient } from '@supabase/supabase-js';
// import type { Database } from './types';

// const SUPABASE_URL = "https://wdlcrzpcmzwmnpdstoci.supabase.co";
// const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndkbGNyenBjbXp3bW5wZHN0b2NpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU4MzU3MTMsImV4cCI6MjA2MTQxMTcxM30.xn_mLFP8cthtEyOB8dL6USulTBbd_Frn8cU8-Ph02Z0";

// export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
